// DXFkeyword.h : ヘッダー ファイル
//		ReadDXF.cpp, DXFMakeClass.cpp で使用する
//		DXFｷｰﾜｰﾄﾞﾃｰﾌﾞﾙのｱｸｾｽ定義

#pragma once

enum enSECTION
{
	SEC_NOSECTION = -1,
	SEC_SECTION, SEC_ENDSEC, SEC_EOF,
		SEC_SECTION_NUM		// [3]
};
enum enSECNAME
{
	SEC_NOSECNAME = -1,
	SEC_HEADER, SEC_TABLES, SEC_BLOCKS, SEC_ENTITIES,
		SEC_SECNAME_NUM		// [4]
};
//
enum
{
	GROUP0 = 0,
	GROUP1,
	GROUP2,
	GROUP3,
	GROUP6,
	GROUP8,
	GROUP9,
	GROUP70,
		GROUP_NUM			// [8]
};
//
enum {
	VALUE10 = 0,	VALUE20,
	VALUE11,		VALUE21,
	VALUE40,		VALUE41,		VALUE42,
	VALUE50,		VALUE51,
	VALUE210,		VALUE220,		VALUE230,
		DXFMAXVALUESIZE		// [12]
};
#define	VALFLG10			0x0001
#define	VALFLG20			0x0002
#define	VALFLG11			0x0004
#define	VALFLG21			0x0008
#define	VALFLG40			0x0010
#define	VALFLG41			0x0020
#define	VALFLG42			0x0040
#define	VALFLG50			0x0100
#define	VALFLG51			0x0200
#define	VALFLG210			0x1000
#define	VALFLG220			0x2000
#define	VALFLG230			0x4000
#define	VALFLG_START		(VALFLG10|VALFLG20)
#define	VALFLG_END			(VALFLG11|VALFLG21)
#define	VALFLG_POINT		(VALFLG_START)
#define	VALFLG_LINE			(VALFLG_START|VALFLG_END)
#define	VALFLG_CIRCLE		(VALFLG_POINT|VALFLG40)
#define	VALFLG_ARC			(VALFLG_CIRCLE|VALFLG50|VALFLG51)
#define	VALFLG_ELLIPSE		(VALFLG_LINE|VALFLG40|VALFLG41|VALFLG42)
#define	VALFLG_TEXT			(VALFLG_POINT)
#define	VALFLG_PLANE		(VALFLG210|VALFLG220|VALFLG230)
//
enum
{
	HEAD_ACADVER = 0,
	HEAD_EXTMIN, HEAD_EXTMAX,
	HEAD_LIMMIN, HEAD_LIMMAX,
		HEAD_NUM		// [5]
};
//
enum
{
	TABLES_TABLE = 0, TABLES_ENDTAB,
	TABLEKEY_LTYPE,
	TABLEKEY_LAYER,
	TABLEKEY_VPORT
};
//
enum
{
	LTYPE_CONTINUOUS = 0,
	LTYPE_DASHED,
	LTYPE_DOT,
	LTYPE_DASHDOT,
	LTYPE_DIVDE,
};
//
enum enENTITIESTYPE
{
	TYPE_SECTION_ERR = -2,
	TYPE_NOTSUPPORT = -1,
	TYPE_POINT = 0,
	TYPE_LINE,
	TYPE_CIRCLE,
	TYPE_ARC,
	TYPE_ELLIPSE,
	TYPE_POLYLINE,
	TYPE_LWPOLYLINE,
	TYPE_SPLINE,
	TYPE_TEXT,
	TYPE_INSERT,
	TYPE_VIEWPORT,
		TYPE_ENTITIES_NUM	// [10]
};
